from __future__ import annotations

ALLOWED_QUERY_PARAMS: dict[str, set[str]] = {
    "/customer": {"name", "organizationNumber", "count", "from", "sorting", "fields"},
    "/supplier": {"name", "organizationNumber", "count", "from", "sorting", "fields"},
    "/employee": {"email", "firstName", "lastName", "count", "from", "sorting", "fields"},
    "/employee/employment": {"employeeId", "count", "from", "sorting", "fields"},
    "/employee/employment/details": {"employmentId", "count", "from", "sorting", "fields"},
    "/employee/employment/workingHoursScheme": {"count", "from", "sorting", "fields"},
    "/department": {"name", "departmentNumber", "departmentManagerId", "isInactive", "count", "from", "sorting", "fields"},
    "/ledger/account": {"id", "number", "isBankAccount", "isInactive", "ledgerType", "isBalanceAccount", "from", "count", "sorting", "fields"},
    "/ledger/vatType": {"count", "from", "sorting", "fields"},
    "/ledger/voucherType": {"count", "from", "sorting", "fields"},
    "/project": {"name", "customerId", "count", "from", "sorting", "fields"},
    "/activity": {"name", "number", "description", "isProjectActivity", "isGeneral", "isChargeable", "isTask", "isInactive", "count", "from", "sorting", "fields"},
    "/timesheet/entry": {"id", "employeeId", "projectId", "activityId", "dateFrom", "dateTo", "comment", "count", "from", "sorting", "fields"},
    "/product": {"name", "number", "count", "from", "sorting", "fields"},
    "/invoice": {
        "customerId",
        "invoiceDateFrom",
        "invoiceDateTo",
        "count",
        "from",
        "sorting",
        "fields",
    },
    "/order": {"customerId", "orderDateFrom", "orderDateTo", "count", "from", "sorting", "fields"},
    "/invoice/paymentType": {"count", "fields"},
    "/incomingInvoice/search": {"voucherId", "invoiceDateFrom", "invoiceDateTo", "invoiceNumber", "vendorId", "status", "from", "count", "sorting", "fields"},
    "/salary/type": {"name", "count", "fields"},
    "/travelExpense": {"employeeId", "count", "fields", "sorting"},
}

ALLOWED_FIELDS: dict[str, set[str]] = {
    "/customer": {"id", "name", "email", "organizationNumber", "isCustomer"},
    "/supplier": {"id", "name", "email", "organizationNumber", "isSupplier", "invoiceEmail"},
    "/employee": {"id", "firstName", "lastName", "email", "displayName"},
    "/employee/employment": {"id", "employee", "startDate", "endDate", "employmentId", "isMainEmployer"},
    "/employee/employment/details": {
        "id",
        "employment",
        "date",
        "employmentType",
        "employmentForm",
        "remunerationType",
        "workingHoursScheme",
        "percentageOfFullTimeEquivalent",
        "annualSalary",
        "hourlyWage",
    },
    "/employee/employment/workingHoursScheme": {"id", "name", "description"},
    "/department": {"id", "name", "displayName", "departmentNumber", "departmentManager", "isInactive"},
    "/ledger/account": {
        "id",
        "number",
        "name",
        "type",
        "ledgerType",
        "isInactive",
        "isBankAccount",
        "isCloseable",
        "vatType",
        "vatLocked",
        "legalVatTypes",
    },
    "/ledger/vatType": {"id", "name", "number", "displayName", "percentage", "deductionPercentage"},
    "/ledger/voucherType": {"id", "name", "displayName"},
    "/project": {"id", "name", "customer", "projectManager", "isFixedPrice", "fixedPrice"},
    "/activity": {"id", "name", "displayName", "rate", "activityType", "isChargeable"},
    "/timesheet/entry": {"id", "project", "activity", "date", "hours", "employee", "comment", "hourlyRate"},
    "/product": {"id", "name", "number", "priceExcludingVatCurrency", "vatType"},
    "/invoice": {
        "id",
        "invoiceDate",
        "invoiceNumber",
        "customer",
        "amountExcludingVat",
        "amountExcludingVatCurrency",
        "paidAmount",
        "amountOutstanding",
        "comment",
        "reference",
    },
    "/order": {"id", "customer", "orderDate", "deliveryDate", "orderLines"},
    "/invoice/paymentType": {"id", "description", "name"},
    "/incomingInvoice/search": {"voucherId", "invoiceHeader", "metadata", "permissions"},
    "/salary/type": {"id", "name", "number"},
    "/travelExpense": {"id", "title", "date", "employee"},
}
